/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DeveloperService } from "../developer.service";
import { DeveloperCreateInput } from "./DeveloperCreateInput";
import { Developer } from "./Developer";
import { DeveloperFindManyArgs } from "./DeveloperFindManyArgs";
import { DeveloperWhereUniqueInput } from "./DeveloperWhereUniqueInput";
import { DeveloperUpdateInput } from "./DeveloperUpdateInput";
import { ServiceFindManyArgs } from "../../service/base/ServiceFindManyArgs";
import { Service } from "../../service/base/Service";
import { ServiceWhereUniqueInput } from "../../service/base/ServiceWhereUniqueInput";

export class DeveloperControllerBase {
  constructor(protected readonly service: DeveloperService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Developer })
  async createDeveloper(
    @common.Body() data: DeveloperCreateInput
  ): Promise<Developer> {
    return await this.service.createDeveloper({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Developer] })
  @ApiNestedQuery(DeveloperFindManyArgs)
  async developers(@common.Req() request: Request): Promise<Developer[]> {
    const args = plainToClass(DeveloperFindManyArgs, request.query);
    return this.service.developers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async developer(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    const result = await this.service.developer({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() data: DeveloperUpdateInput
  ): Promise<Developer | null> {
    try {
      return await this.service.updateDeveloper({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Developer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDeveloper(
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Developer | null> {
    try {
      return await this.service.deleteDeveloper({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/services")
  @ApiNestedQuery(ServiceFindManyArgs)
  async findServices(
    @common.Req() request: Request,
    @common.Param() params: DeveloperWhereUniqueInput
  ): Promise<Service[]> {
    const query = plainToClass(ServiceFindManyArgs, request.query);
    const results = await this.service.findServices(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,

        developer: {
          select: {
            id: true,
          },
        },

        id: true,
        label: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/services")
  async connectServices(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        connect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/services")
  async updateServices(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        set: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/services")
  async disconnectServices(
    @common.Param() params: DeveloperWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        disconnect: body,
      },
    };
    await this.service.updateDeveloper({
      where: params,
      data,
      select: { id: true },
    });
  }
}
